const HOUR_IN_MS = 60 * 60 * 1000;

export const EMAIL_VERIFICATION_TOKEN_TTL_MS = 24 * HOUR_IN_MS;
export const PASSWORD_RESET_TOKEN_TTL_MS = HOUR_IN_MS;
export const EMAIL_CHANGE_TOKEN_TTL_MS = HOUR_IN_MS;
